### PR TITLE
Support links inside figcaption

### PR DESCRIPTION
**Pull request by svendroid**
Adds markdown support for caption content e.g. to support links for attribution as described here #3 

Markdown Input:
```markdown
![Imagename from [creator](https://creator.com) under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/)](./images/testimage.png)
```

HTML Output for figcaption:
```html
<figcaption class="md-figure-caption">Imagename from <a href="https://creator.com">creator</a> under <a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a></figcaption>
```

### CODE REVIEW

**Review by tkhquang — APPROVED** [review]
LGTM, will bump on this weekend.

Thank you for contribution!

**Comment by svendroid** [comment]
Hi @tkhquang could you release the changes as a new version on npm?

**Comment by tkhquang** [comment]
> Hi @tkhquang could you release the changes as a new version on npm?

Sorry for taking this so long. I had some problems with my PC back then and when it's fixed I... totally forgot about this. New version is up now!
Thanks again for contributing! 👍

**Comment by svendroid** [comment]
Thanks for the quick reply. Now I can switch to the official version in my project. :)

**Pull request merged**
